#!/usr/bin/env bash

set -euo pipefail

rebar3 escriptize

ERL_ROOT=$(erl -noinput -eval 'io:format("~s",[code:root_dir()]),halt().')
ERL_DIR=$(basename $ERL_ROOT)
rm -rf _build/emqx_data_converter
cp -R ${ERL_ROOT%/} _build/
mv _build/default/bin/emqx_data_converter _build/$ERL_DIR/bin/emqx_data_converter.escript
cp -f _build/$ERL_DIR/bin/escript _build/$ERL_DIR/bin/emqx_data_converter
mkdir _build/emqx_data_converter
mv _build/$ERL_DIR/* _build/emqx_data_converter
tar -czf _build/emqx_data_converter.tar.gz -C _build emqx_data_converter
rm -rf _build/emqx_data_converter
rm -rf _build/$ERL_DIR

UNAME="$(uname -s)"
case "$UNAME" in
    Darwin)
        DIST='macos'
        VERSION_ID="$(sw_vers | grep 'ProductVersion' | cut -d':' -f 2 | cut -d'.' -f1 | tr -d ' \t')"
        SYSTEM="${DIST}${VERSION_ID}"
        ;;
    Linux)
        # /etc/os-release on amazon linux 2 contains both rhel and centos strings
        if grep -q -i 'amzn' /etc/*-release; then
            DIST='amzn'
            VERSION_ID="$(sed -n '/^VERSION_ID=/p' /etc/os-release | sed -r 's/VERSION_ID=(.*)/\1/g' | sed 's/"//g')"
        elif grep -q -i 'rhel' /etc/*-release; then
            DIST='el'
            VERSION_ID="$(rpm --eval '%{rhel}')"
        else
            DIST="$(sed -n '/^ID=/p' /etc/os-release | sed -r 's/ID=(.*)/\1/g' | sed 's/"//g')"
            VERSION_ID="$(sed -n '/^VERSION_ID=/p' /etc/os-release | sed -r 's/VERSION_ID=(.*)/\1/g' | sed 's/"//g')"
        fi
        SYSTEM="$(echo "${DIST}${VERSION_ID}" | sed -r 's/([a-zA-Z]*)-.*/\1/g')"
        ;;
esac

ARCH="$(uname -m)"
case "$ARCH" in
    x86_64)
        ARCH='amd64'
        ;;
    aarch64)
        ARCH='arm64'
        ;;
    arm*)
        ARCH=arm
        ;;
esac

VSN="${VSN:-$(grep -E ".+vsn.+" _build/default/lib/emqx_data_converter/ebin/emqx_data_converter.app | cut -d '"' -f2)}"
cp "./_build/emqx_data_converter.tar.gz" "./emqx-data-converter-${VSN}-${SYSTEM}-${ARCH}.tar.gz"
